source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'mysql2'
gem 'gravatar_image_tag', '1.0.0.pre2'
gem 'jquery-rails'
gem "will_paginate", :git => "https://github.com/p7r/will_paginate.git", :branch => "rails3"

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'rspec-rails', '2.6.1'
  gem 'annotate', '>=2.5.0'
  gem 'faker', '0.3.1'
end

group :test do
  gem 'rspec-rails', '2.6.1'
  gem 'webrat', '0.7.1'
  gem 'factory_girl_rails', '1.0'
end